services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongo_database
    environment:
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  mysql:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./Order-service/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
